"""
Real 2nd-year B.Tech male student roster (2025 batch), on CGPA-merit-list
basis, ranks 1-260. This now covers BOTH hostels:

  - Ranks 1-102   -> GSV Campus Hostel  (Triple Sharing)
  - Ranks 103+     -> Stanza Living Hostel (Double Sharing)

`hostelType` here is only the STARTING assignment used to seed a fresh
database. Once the app is running, a student's actual hostel can change
(opt-out / promotion), so the live value always lives in the `students`
table in the database, not in this file.
"""

GSV_HOSTEL_CAPACITY = 102

REAL_STUDENTS = [
    {"roll": '25AI1034', "name": 'Prashant', "branch": 'AIDS', "cgpa": 9.93, "rank": 1, "hostelType": 'GSV'},
    {"roll": '25AE1008', "name": 'Arka Kumar Bagchi', "branch": 'AE', "cgpa": 9.64, "rank": 2, "hostelType": 'GSV'},
    {"roll": '25EC1020', "name": 'Hardik Bhatt', "branch": 'ECE', "cgpa": 9.45, "rank": 3, "hostelType": 'GSV'},
    {"roll": '25ME1034', "name": 'Omm Suman', "branch": 'ME', "cgpa": 9.4, "rank": 4, "hostelType": 'GSV'},
    {"roll": '25AE1015', "name": 'Hiten Dubey', "branch": 'AE', "cgpa": 9.34, "rank": 5, "hostelType": 'GSV'},
    {"roll": '25EC1027', "name": 'Kshitij Dubey', "branch": 'ECE', "cgpa": 9.3, "rank": 6, "hostelType": 'GSV'},
    {"roll": '25AI1035', "name": 'Prince', "branch": 'AIDS', "cgpa": 9.3, "rank": 7, "hostelType": 'GSV'},
    {"roll": '25AI1008', "name": 'Anurag Singh', "branch": 'AIDS', "cgpa": 9.28, "rank": 8, "hostelType": 'GSV'},
    {"roll": '25EE1034', "name": 'Sachin Kumar Patel', "branch": 'EE', "cgpa": 9.23, "rank": 9, "hostelType": 'GSV'},
    {"roll": '25ME1008', "name": 'Aryan Raj', "branch": 'ME', "cgpa": 9.23, "rank": 10, "hostelType": 'GSV'},
    {"roll": '25CE1025', "name": 'Deepak Yadav', "branch": 'CE', "cgpa": 9.1, "rank": 11, "hostelType": 'GSV'},
    {"roll": '25ME1014', "name": 'Durgesh Nayak', "branch": 'ME', "cgpa": 9.08, "rank": 12, "hostelType": 'GSV'},
    {"roll": '25EE1027', "name": 'Piyush Kumar', "branch": 'EE', "cgpa": 9.03, "rank": 13, "hostelType": 'GSV'},
    {"roll": '25ME1020', "name": 'Hrishi Ajoykumar', "branch": 'ME', "cgpa": 9.03, "rank": 14, "hostelType": 'GSV'},
    {"roll": '25EC1021', "name": 'Hari Om Mishra', "branch": 'ECE', "cgpa": 9.0, "rank": 15, "hostelType": 'GSV'},
    {"roll": '25CE1042', "name": 'Parth Kumar', "branch": 'CE', "cgpa": 8.98, "rank": 16, "hostelType": 'GSV'},
    {"roll": '25AI1036', "name": 'Priyam Alok', "branch": 'AIDS', "cgpa": 8.98, "rank": 17, "hostelType": 'GSV'},
    {"roll": '25EC1052', "name": 'Sarthak Bansal', "branch": 'ECE', "cgpa": 8.95, "rank": 18, "hostelType": 'GSV'},
    {"roll": '25EE1012', "name": 'Bhavya Soni', "branch": 'EE', "cgpa": 8.93, "rank": 19, "hostelType": 'GSV'},
    {"roll": '25AE1038', "name": 'Yuvarajaa S', "branch": 'AE', "cgpa": 8.91, "rank": 20, "hostelType": 'GSV'},
    {"roll": '25ME1040', "name": 'Samarthansh Ashwinikumar Totawar', "branch": 'ME', "cgpa": 8.88, "rank": 21, "hostelType": 'GSV'},
    {"roll": '25AI1017', "name": 'Dixit Patel', "branch": 'AIDS', "cgpa": 8.88, "rank": 22, "hostelType": 'GSV'},
    {"roll": '25AI1025', "name": 'Manas Sachin Khapare', "branch": 'AIDS', "cgpa": 8.88, "rank": 23, "hostelType": 'GSV'},
    {"roll": '25EC1019', "name": 'Govind Kumar Dubey', "branch": 'ECE', "cgpa": 8.85, "rank": 24, "hostelType": 'GSV'},
    {"roll": '25AI1056', "name": 'Vidhu Sharma', "branch": 'AIDS', "cgpa": 8.85, "rank": 25, "hostelType": 'GSV'},
    {"roll": '25AE1021', "name": 'Mohit Raj', "branch": 'AE', "cgpa": 8.84, "rank": 26, "hostelType": 'GSV'},
    {"roll": '25EC1007', "name": 'Arjun Yadav', "branch": 'ECE', "cgpa": 8.83, "rank": 27, "hostelType": 'GSV'},
    {"roll": '25EE1002', "name": 'Abhishek Kumar', "branch": 'EE', "cgpa": 8.73, "rank": 28, "hostelType": 'GSV'},
    {"roll": '25AI1019', "name": 'Gulshan Kumar Shah', "branch": 'AIDS', "cgpa": 8.68, "rank": 29, "hostelType": 'GSV'},
    {"roll": '25EE1036', "name": 'Sagar Yadav', "branch": 'EE', "cgpa": 8.65, "rank": 30, "hostelType": 'GSV'},
    {"roll": '25EE1042', "name": 'Shubh Anand', "branch": 'EE', "cgpa": 8.65, "rank": 31, "hostelType": 'GSV'},
    {"roll": '25AI1022', "name": 'Lakshya Kumawat', "branch": 'AIDS', "cgpa": 8.65, "rank": 32, "hostelType": 'GSV'},
    {"roll": '25AI1053', "name": 'Suraj Prakash', "branch": 'AIDS', "cgpa": 8.6, "rank": 33, "hostelType": 'GSV'},
    {"roll": '25EC1009', "name": 'Avinash Mishra', "branch": 'ECE', "cgpa": 8.58, "rank": 34, "hostelType": 'GSV'},
    {"roll": '25EE1015', "name": 'Daksh Jigneshbhai Shrimali', "branch": 'EE', "cgpa": 8.58, "rank": 35, "hostelType": 'GSV'},
    {"roll": '25CE1027', "name": 'Devesh Kumar', "branch": 'CE', "cgpa": 8.58, "rank": 36, "hostelType": 'GSV'},
    {"roll": '25AI1033', "name": 'Prasad Saurav Ramanand', "branch": 'AIDS', "cgpa": 8.58, "rank": 37, "hostelType": 'GSV'},
    {"roll": '25AI1015', "name": 'Bhut Meet Umeshbhai', "branch": 'AIDS', "cgpa": 8.55, "rank": 38, "hostelType": 'GSV'},
    {"roll": '25CE1034', "name": 'Kumar Aditya', "branch": 'CE', "cgpa": 8.53, "rank": 39, "hostelType": 'GSV'},
    {"roll": '25AI1014', "name": 'Bhanwar Lal', "branch": 'AIDS', "cgpa": 8.53, "rank": 40, "hostelType": 'GSV'},
    {"roll": '25EC1005', "name": 'Akshat Asati', "branch": 'ECE', "cgpa": 8.5, "rank": 41, "hostelType": 'GSV'},
    {"roll": '25EE1040', "name": 'Shivanand Vishal Deshpande', "branch": 'EE', "cgpa": 8.5, "rank": 42, "hostelType": 'GSV'},
    {"roll": '25AI1003', "name": 'Ajeet Kumar Yadav', "branch": 'AIDS', "cgpa": 8.5, "rank": 43, "hostelType": 'GSV'},
    {"roll": '25ME1032', "name": 'Naveen Rao', "branch": 'ME', "cgpa": 8.48, "rank": 44, "hostelType": 'GSV'},
    {"roll": '25AE1001', "name": 'Aashish Barnwal', "branch": 'AE', "cgpa": 8.45, "rank": 45, "hostelType": 'GSV'},
    {"roll": '25AE1014', "name": 'Hemant Sharma', "branch": 'AE', "cgpa": 8.45, "rank": 46, "hostelType": 'GSV'},
    {"roll": '25AE1018', "name": 'Kartik Rajpurohit', "branch": 'AE', "cgpa": 8.43, "rank": 47, "hostelType": 'GSV'},
    {"roll": '25AI1043', "name": 'Sahu Vibek Apurba', "branch": 'AIDS', "cgpa": 8.43, "rank": 48, "hostelType": 'GSV'},
    {"roll": '25EE1028', "name": 'Priyanshu Choudhary', "branch": 'EE', "cgpa": 8.35, "rank": 49, "hostelType": 'GSV'},
    {"roll": '25AI1023', "name": 'Love Rajawat', "branch": 'AIDS', "cgpa": 8.35, "rank": 50, "hostelType": 'GSV'},
    {"roll": '25AI1040', "name": 'Rudransh Mishra', "branch": 'AIDS', "cgpa": 8.35, "rank": 51, "hostelType": 'GSV'},
    {"roll": '25EE1043', "name": 'Shubham Kumar Gupta', "branch": 'EE', "cgpa": 8.33, "rank": 52, "hostelType": 'GSV'},
    {"roll": '25EE1006', "name": 'Arin Roy', "branch": 'EE', "cgpa": 8.3, "rank": 53, "hostelType": 'GSV'},
    {"roll": '25EE1041', "name": 'Shourya Tripathi', "branch": 'EE', "cgpa": 8.3, "rank": 54, "hostelType": 'GSV'},
    {"roll": '25CE1049', "name": 'Shreyash Malviya', "branch": 'CE', "cgpa": 8.3, "rank": 55, "hostelType": 'GSV'},
    {"roll": '25AE1006', "name": 'Amit Kumar', "branch": 'AE', "cgpa": 8.3, "rank": 56, "hostelType": 'GSV'},
    {"roll": '25EC1050', "name": 'Sapkal Pawan Kaduba', "branch": 'ECE', "cgpa": 8.28, "rank": 57, "hostelType": 'GSV'},
    {"roll": '25EE1024', "name": 'Mayank Raj', "branch": 'EE', "cgpa": 8.28, "rank": 58, "hostelType": 'GSV'},
    {"roll": '25CE1046', "name": 'Raj Aaryan', "branch": 'CE', "cgpa": 8.28, "rank": 59, "hostelType": 'GSV'},
    {"roll": '25CE1058', "name": 'Utkarsh Rai', "branch": 'CE', "cgpa": 8.28, "rank": 60, "hostelType": 'GSV'},
    {"roll": '25AI1020', "name": 'Kartikeya Jain', "branch": 'AIDS', "cgpa": 8.28, "rank": 61, "hostelType": 'GSV'},
    {"roll": '25EC1043', "name": 'Rohit Kumawat', "branch": 'ECE', "cgpa": 8.25, "rank": 62, "hostelType": 'GSV'},
    {"roll": '25EC1061', "name": 'Vikramaditya Sanecha', "branch": 'ECE', "cgpa": 8.25, "rank": 63, "hostelType": 'GSV'},
    {"roll": '25AE1009', "name": 'Arpit Bhardwaj', "branch": 'AE', "cgpa": 8.23, "rank": 64, "hostelType": 'GSV'},
    {"roll": '25EC1037', "name": 'Piyush Saini', "branch": 'ECE', "cgpa": 8.2, "rank": 65, "hostelType": 'GSV'},
    {"roll": '25AI1042', "name": 'Sahitya Panwar', "branch": 'AIDS', "cgpa": 8.2, "rank": 66, "hostelType": 'GSV'},
    {"roll": '25EC1022', "name": 'Harsh Kumar', "branch": 'ECE', "cgpa": 8.18, "rank": 67, "hostelType": 'GSV'},
    {"roll": '25AE1002', "name": 'Abhishek Kumar', "branch": 'AE', "cgpa": 8.14, "rank": 68, "hostelType": 'GSV'},
    {"roll": '25EC1010', "name": 'Bhavesh Choudhary', "branch": 'ECE', "cgpa": 8.13, "rank": 69, "hostelType": 'GSV'},
    {"roll": '25EC1023', "name": 'Jha Mayank Ranjit', "branch": 'ECE', "cgpa": 8.13, "rank": 70, "hostelType": 'GSV'},
    {"roll": '25EE1004', "name": 'Anish Kumar', "branch": 'EE', "cgpa": 8.13, "rank": 71, "hostelType": 'GSV'},
    {"roll": '25AI1004', "name": 'Akhil Jobbi', "branch": 'AIDS', "cgpa": 8.13, "rank": 72, "hostelType": 'GSV'},
    {"roll": '25EE1026', "name": 'Nishant Kumar', "branch": 'EE', "cgpa": 8.1, "rank": 73, "hostelType": 'GSV'},
    {"roll": '25ME1029', "name": 'Maurya Priyam Ramrajbhai', "branch": 'ME', "cgpa": 8.1, "rank": 74, "hostelType": 'GSV'},
    {"roll": '25CE1028', "name": 'Eshatva Kumar', "branch": 'CE', "cgpa": 8.1, "rank": 75, "hostelType": 'GSV'},
    {"roll": '25AI1002', "name": 'Aditya Singhal', "branch": 'AIDS', "cgpa": 8.1, "rank": 76, "hostelType": 'GSV'},
    {"roll": '25AE1036', "name": 'Vedant Jitendra Deshmukh', "branch": 'AE', "cgpa": 8.07, "rank": 77, "hostelType": 'GSV'},
    {"roll": '25EC1004', "name": 'Akash Singh', "branch": 'ECE', "cgpa": 8.05, "rank": 78, "hostelType": 'GSV'},
    {"roll": '25AI1048', "name": 'Shorya Jain', "branch": 'AIDS', "cgpa": 8.05, "rank": 79, "hostelType": 'GSV'},
    {"roll": '25AE1025', "name": 'Sagar Malviya', "branch": 'AE', "cgpa": 8.05, "rank": 80, "hostelType": 'GSV'},
    {"roll": '25EC1006', "name": 'Anmol Gupta', "branch": 'ECE', "cgpa": 8.03, "rank": 81, "hostelType": 'GSV'},
    {"roll": '25EC1038', "name": 'Prem Prabhakar', "branch": 'ECE', "cgpa": 8.0, "rank": 82, "hostelType": 'GSV'},
    {"roll": '25EC1045', "name": 'Sachin Nain', "branch": 'ECE', "cgpa": 8.0, "rank": 83, "hostelType": 'GSV'},
    {"roll": '25EC1032', "name": 'Manish Laxmi Narayan Sharma', "branch": 'ECE', "cgpa": 7.98, "rank": 84, "hostelType": 'GSV'},
    {"roll": '25AI1011', "name": 'Ayush Kumar Singh', "branch": 'AIDS', "cgpa": 7.98, "rank": 85, "hostelType": 'GSV'},
    {"roll": '25CE1040', "name": 'Niraj Kumar', "branch": 'CE', "cgpa": 7.93, "rank": 86, "hostelType": 'GSV'},
    {"roll": '25CE1001', "name": 'Aayush Kashyap', "branch": 'CE', "cgpa": 7.9, "rank": 87, "hostelType": 'GSV'},
    {"roll": '25AI1007', "name": 'Aniket Singh', "branch": 'AIDS', "cgpa": 7.88, "rank": 88, "hostelType": 'GSV'},
    {"roll": '25ME1030', "name": 'Mritunjay Raj', "branch": 'ME', "cgpa": 7.85, "rank": 89, "hostelType": 'GSV'},
    {"roll": '25ME1042', "name": 'Shrimukh Tripathi', "branch": 'ME', "cgpa": 7.85, "rank": 90, "hostelType": 'GSV'},
    {"roll": '25EC1030', "name": 'Lucky Tomar', "branch": 'ECE', "cgpa": 7.83, "rank": 91, "hostelType": 'GSV'},
    {"roll": '25EC1060', "name": 'Vikram Singh', "branch": 'ECE', "cgpa": 7.8, "rank": 92, "hostelType": 'GSV'},
    {"roll": '25EE1030', "name": 'Rishabh Kumar', "branch": 'EE', "cgpa": 7.8, "rank": 93, "hostelType": 'GSV'},
    {"roll": '25CE1020', "name": 'Chaudhary Mridul', "branch": 'CE', "cgpa": 7.8, "rank": 94, "hostelType": 'GSV'},
    {"roll": '25ME1002', "name": 'Abhishek Kumar', "branch": 'ME', "cgpa": 7.78, "rank": 95, "hostelType": 'GSV'},
    {"roll": '25CE1009', "name": 'Amrit Shekhar', "branch": 'CE', "cgpa": 7.78, "rank": 96, "hostelType": 'GSV'},
    {"roll": '25AE1016', "name": 'Hotkar Aryan Vinayak', "branch": 'AE', "cgpa": 7.75, "rank": 97, "hostelType": 'GSV'},
    {"roll": '25AE1031', "name": 'Sinku Kumar', "branch": 'AE', "cgpa": 7.75, "rank": 98, "hostelType": 'GSV'},
    {"roll": '25CE1036', "name": 'Lunavath Sathya', "branch": 'CE', "cgpa": 7.75, "rank": 99, "hostelType": 'GSV'},
    {"roll": '25EC1047', "name": 'Samyak Jain', "branch": 'ECE', "cgpa": 7.7, "rank": 100, "hostelType": 'GSV'},
    {"roll": '25EE1003', "name": 'Aditya Dev', "branch": 'EE', "cgpa": 7.7, "rank": 101, "hostelType": 'GSV'},
    {"roll": '25ME1036', "name": 'Prayag Solanki', "branch": 'ME', "cgpa": 7.68, "rank": 102, "hostelType": 'GSV'},
    {"roll": '25EE1019', "name": 'Harsadeepta Upadhyay', "branch": 'EE', "cgpa": 7.65, "rank": 103, "hostelType": 'STANZA'},
    {"roll": '25CE1007', "name": 'Ambuj Mishra', "branch": 'CE', "cgpa": 7.65, "rank": 104, "hostelType": 'STANZA'},
    {"roll": '25CE1008', "name": 'Amit Mehra', "branch": 'CE', "cgpa": 7.63, "rank": 105, "hostelType": 'STANZA'},
    {"roll": '25AE1004', "name": 'Adhava S R', "branch": 'AE', "cgpa": 7.59, "rank": 106, "hostelType": 'STANZA'},
    {"roll": '25EC1015', "name": 'Dhruv Meena', "branch": 'ECE', "cgpa": 7.58, "rank": 107, "hostelType": 'STANZA'},
    {"roll": '25EC1053', "name": 'Shashank Dubey', "branch": 'ECE', "cgpa": 7.58, "rank": 108, "hostelType": 'STANZA'},
    {"roll": '25EE1045', "name": 'Suraj Yadav', "branch": 'EE', "cgpa": 7.58, "rank": 109, "hostelType": 'STANZA'},
    {"roll": '25AE1029', "name": 'Saurabh Sanjay Ahire', "branch": 'AE', "cgpa": 7.57, "rank": 110, "hostelType": 'STANZA'},
    {"roll": '25EC1056', "name": 'Somala Nithin Reddy', "branch": 'ECE', "cgpa": 7.55, "rank": 111, "hostelType": 'STANZA'},
    {"roll": '25ME1026', "name": 'Lakshya Gangwar', "branch": 'ME', "cgpa": 7.55, "rank": 112, "hostelType": 'STANZA'},
    {"roll": '25AI1032', "name": 'Piyush Raj', "branch": 'AIDS', "cgpa": 7.55, "rank": 113, "hostelType": 'STANZA'},
    {"roll": '25ME1001', "name": 'Abhinav Aryan', "branch": 'ME', "cgpa": 7.53, "rank": 114, "hostelType": 'STANZA'},
    {"roll": '25EE1052', "name": 'Youraj Kumar', "branch": 'EE', "cgpa": 7.5, "rank": 115, "hostelType": 'STANZA'},
    {"roll": '25AE1033', "name": 'Sourish Zirota', "branch": 'AE', "cgpa": 7.5, "rank": 116, "hostelType": 'STANZA'},
    {"roll": '25EC1059', "name": 'Suraj Kumar Jha', "branch": 'ECE', "cgpa": 7.48, "rank": 117, "hostelType": 'STANZA'},
    {"roll": '25EE1001', "name": 'Abhinav Kumar', "branch": 'EE', "cgpa": 7.45, "rank": 118, "hostelType": 'STANZA'},
    {"roll": '25ME1024', "name": 'Kshitij Aryan', "branch": 'ME', "cgpa": 7.45, "rank": 119, "hostelType": 'STANZA'},
    {"roll": '25CE1043', "name": 'Prakash Kumar', "branch": 'CE', "cgpa": 7.43, "rank": 120, "hostelType": 'STANZA'},
    {"roll": '25ME1015', "name": 'Gaurav', "branch": 'ME', "cgpa": 7.4, "rank": 121, "hostelType": 'STANZA'},
    {"roll": '25ME1004', "name": 'Aditya Jay', "branch": 'ME', "cgpa": 7.38, "rank": 122, "hostelType": 'STANZA'},
    {"roll": '25CE1004', "name": 'Aditya Kumar Choudhary', "branch": 'CE', "cgpa": 7.38, "rank": 123, "hostelType": 'STANZA'},
    {"roll": '25EE1005', "name": 'Ankit Kumar Kushwaha', "branch": 'EE', "cgpa": 7.35, "rank": 124, "hostelType": 'STANZA'},
    {"roll": '25AE1020', "name": 'Manish Kumar', "branch": 'AE', "cgpa": 7.34, "rank": 125, "hostelType": 'STANZA'},
    {"roll": '25EE1032', "name": 'Ritvik Dewangan', "branch": 'EE', "cgpa": 7.3, "rank": 126, "hostelType": 'STANZA'},
    {"roll": '25AE1030', "name": 'Shreyas Sanjay Chate', "branch": 'AE', "cgpa": 7.3, "rank": 127, "hostelType": 'STANZA'},
    {"roll": '25CE1022', "name": 'Dara Dominic Blesson', "branch": 'CE', "cgpa": 7.23, "rank": 128, "hostelType": 'STANZA'},
    {"roll": '25CE1053', "name": 'Swaroop Ranjan Samal', "branch": 'CE', "cgpa": 7.23, "rank": 129, "hostelType": 'STANZA'},
    {"roll": '25ME1023', "name": 'Krishan Yadav', "branch": 'ME', "cgpa": 7.2, "rank": 130, "hostelType": 'STANZA'},
    {"roll": '25ME1035', "name": 'Prashant Gupta', "branch": 'ME', "cgpa": 7.18, "rank": 131, "hostelType": 'STANZA'},
    {"roll": '25EC1058', "name": 'Sunny Kumar', "branch": 'ECE', "cgpa": 7.15, "rank": 132, "hostelType": 'STANZA'},
    {"roll": '25EE1046', "name": 'Tejas Shrivastava', "branch": 'EE', "cgpa": 7.15, "rank": 133, "hostelType": 'STANZA'},
    {"roll": '25CE1044', "name": 'Prakhar Priyam', "branch": 'CE', "cgpa": 7.15, "rank": 134, "hostelType": 'STANZA'},
    {"roll": '25AI1001', "name": 'Aditya Kumar', "branch": 'AIDS', "cgpa": 7.15, "rank": 135, "hostelType": 'STANZA'},
    {"roll": '25AE1024', "name": 'Prayagraj Singh', "branch": 'AE', "cgpa": 7.14, "rank": 136, "hostelType": 'STANZA'},
    {"roll": '25ME1025', "name": 'Kumar Harsh', "branch": 'ME', "cgpa": 7.13, "rank": 137, "hostelType": 'STANZA'},
    {"roll": '25CE1002', "name": 'Abhishek Kumar', "branch": 'CE', "cgpa": 7.13, "rank": 138, "hostelType": 'STANZA'},
    {"roll": '25AI1012', "name": 'Ayush Yadav', "branch": 'AIDS', "cgpa": 7.13, "rank": 139, "hostelType": 'STANZA'},
    {"roll": '25EE1008', "name": 'Ayush Kumar', "branch": 'EE', "cgpa": 7.08, "rank": 140, "hostelType": 'STANZA'},
    {"roll": '25AE1028', "name": 'Satyam Pal', "branch": 'AE', "cgpa": 7.02, "rank": 141, "hostelType": 'STANZA'},
    {"roll": '25CE1038', "name": 'Mohammad Zakee Ansari', "branch": 'CE', "cgpa": 7.0, "rank": 142, "hostelType": 'STANZA'},
    {"roll": '25AI1041', "name": 'Rutvik', "branch": 'AIDS', "cgpa": 7.0, "rank": 143, "hostelType": 'STANZA'},
    {"roll": '25ME1007', "name": 'Arjun Meghwal', "branch": 'ME', "cgpa": 6.98, "rank": 144, "hostelType": 'STANZA'},
    {"roll": '25EC1025', "name": 'Krish Anand', "branch": 'ECE', "cgpa": 6.95, "rank": 145, "hostelType": 'STANZA'},
    {"roll": '25EC1055', "name": 'Shubham Kumar', "branch": 'ECE', "cgpa": 6.95, "rank": 146, "hostelType": 'STANZA'},
    {"roll": '25EE1023', "name": 'Masulu Rohith Royal', "branch": 'EE', "cgpa": 6.9, "rank": 147, "hostelType": 'STANZA'},
    {"roll": '25CE1029', "name": 'Harshal Das', "branch": 'CE', "cgpa": 6.9, "rank": 148, "hostelType": 'STANZA'},
    {"roll": '25EC1018', "name": 'Gautam Kumar', "branch": 'ECE', "cgpa": 6.85, "rank": 149, "hostelType": 'STANZA'},
    {"roll": '25EC1017', "name": 'Dushyant Kasana', "branch": 'ECE', "cgpa": 6.78, "rank": 150, "hostelType": 'STANZA'},
    {"roll": '25EC1003', "name": 'Akash Kumar', "branch": 'ECE', "cgpa": 6.7, "rank": 151, "hostelType": 'STANZA'},
    {"roll": '25ME1049', "name": 'Vempadapu Praveen Praharsha', "branch": 'ME', "cgpa": 6.7, "rank": 152, "hostelType": 'STANZA'},
    {"roll": '25AI1028', "name": 'Naman Jain', "branch": 'AIDS', "cgpa": 6.68, "rank": 153, "hostelType": 'STANZA'},
    {"roll": '25CE1031', "name": 'Junghare Sujal Harshad', "branch": 'CE', "cgpa": 6.58, "rank": 154, "hostelType": 'STANZA'},
    {"roll": '25ME1041', "name": 'Shlok Sharma', "branch": 'ME', "cgpa": 6.55, "rank": 155, "hostelType": 'STANZA'},
    {"roll": '25ME1044', "name": 'Vagheeshatheertha K S', "branch": 'ME', "cgpa": 6.55, "rank": 156, "hostelType": 'STANZA'},
    {"roll": '25EE1009', "name": 'Ayush Kumar Choudhary', "branch": 'EE', "cgpa": 6.53, "rank": 157, "hostelType": 'STANZA'},
    {"roll": '25AI1045', "name": 'Satwik Prakash', "branch": 'AIDS', "cgpa": 6.53, "rank": 158, "hostelType": 'STANZA'},
    {"roll": '25AI1009', "name": 'Arav Kumar Yadav', "branch": 'AIDS', "cgpa": 6.5, "rank": 159, "hostelType": 'STANZA'},
    {"roll": '25EE1048', "name": 'Uttam Kumar', "branch": 'EE', "cgpa": 6.38, "rank": 160, "hostelType": 'STANZA'},
    {"roll": '25EE1039', "name": 'Shaurya Gupta', "branch": 'EE', "cgpa": 6.35, "rank": 161, "hostelType": 'STANZA'},
    {"roll": '25ME1016', "name": 'Gopal Kumar', "branch": 'ME', "cgpa": 6.33, "rank": 162, "hostelType": 'STANZA'},
    {"roll": '25EC1039', "name": 'Prince Chaurasiya', "branch": 'ECE', "cgpa": 6.3, "rank": 163, "hostelType": 'STANZA'},
    {"roll": '25CE1011', "name": 'Anuj Kumar', "branch": 'CE', "cgpa": 6.3, "rank": 164, "hostelType": 'STANZA'},
    {"roll": '25CE1056', "name": 'Tanmay Bhardwaj', "branch": 'CE', "cgpa": 6.28, "rank": 165, "hostelType": 'STANZA'},
    {"roll": '25ME1017', "name": 'Harshit Sharma', "branch": 'ME', "cgpa": 6.25, "rank": 166, "hostelType": 'STANZA'},
    {"roll": '25AI1016', "name": 'Bollepalli Ishanth Chandra', "branch": 'AIDS', "cgpa": 6.23, "rank": 167, "hostelType": 'STANZA'},
    {"roll": '25ME1048', "name": 'Veera Niranjan E S', "branch": 'ME', "cgpa": 6.18, "rank": 168, "hostelType": 'STANZA'},
    {"roll": '25ME1031', "name": 'Naru Manohar', "branch": 'ME', "cgpa": 6.08, "rank": 169, "hostelType": 'STANZA'},
    {"roll": '25EC1046', "name": 'Sameer Ranjan Maharana', "branch": 'ECE', "cgpa": 6.05, "rank": 170, "hostelType": 'STANZA'},
    {"roll": '25CE1021', "name": 'Damodar Pal', "branch": 'CE', "cgpa": 6.05, "rank": 171, "hostelType": 'STANZA'},
    {"roll": '25CE1030', "name": 'Hitesh', "branch": 'CE', "cgpa": 6.05, "rank": 172, "hostelType": 'STANZA'},
    {"roll": '25AE1026', "name": 'Sahil', "branch": 'AE', "cgpa": 6.05, "rank": 173, "hostelType": 'STANZA'},
    {"roll": '25EC1012', "name": 'Dayam Vivek', "branch": 'ECE', "cgpa": 6.0, "rank": 174, "hostelType": 'STANZA'},
    {"roll": '25AI1039', "name": 'Rashibh Yadav', "branch": 'AIDS', "cgpa": 6.0, "rank": 175, "hostelType": 'STANZA'},
    {"roll": '25AI1049', "name": 'Shriyansh', "branch": 'AIDS', "cgpa": 6.0, "rank": 176, "hostelType": 'STANZA'},
    {"roll": '25EC1051', "name": 'Saroj Vishal', "branch": 'ECE', "cgpa": 5.98, "rank": 177, "hostelType": 'STANZA'},
    {"roll": '25EC1001', "name": 'Abhyudaya Raj', "branch": 'ECE', "cgpa": 5.93, "rank": 178, "hostelType": 'STANZA'},
    {"roll": '25EC1048', "name": 'Sanidhya Singh', "branch": 'ECE', "cgpa": 5.9, "rank": 179, "hostelType": 'STANZA'},
    {"roll": '25AE1003', "name": 'Adarsh Kumar', "branch": 'AE', "cgpa": 5.86, "rank": 180, "hostelType": 'STANZA'},
    {"roll": '25EE1007', "name": 'Arya Pratap Somvanshi', "branch": 'EE', "cgpa": 5.83, "rank": 181, "hostelType": 'STANZA'},
    {"roll": '25AI1005', "name": 'Akshit Kumar', "branch": 'AIDS', "cgpa": 5.83, "rank": 182, "hostelType": 'STANZA'},
    {"roll": '25CE1052', "name": 'Suman Kumar', "branch": 'CE', "cgpa": 5.8, "rank": 183, "hostelType": 'STANZA'},
    {"roll": '25AE1023', "name": 'Pallu Shashidhar Reddy', "branch": 'AE', "cgpa": 5.66, "rank": 184, "hostelType": 'STANZA'},
    {"roll": '25CE1023', "name": 'Datla Pavan Sidhardha Karthikeya Varma', "branch": 'CE', "cgpa": 5.65, "rank": 185, "hostelType": 'STANZA'},
    {"roll": '25ME1009', "name": 'Avayav Shukla', "branch": 'ME', "cgpa": 5.58, "rank": 186, "hostelType": 'STANZA'},
    {"roll": '25CE1015', "name": 'Ayush Bari', "branch": 'CE', "cgpa": 5.58, "rank": 187, "hostelType": 'STANZA'},
    {"roll": '25EE1053', "name": 'Yug Agrawal', "branch": 'EE', "cgpa": 5.55, "rank": 188, "hostelType": 'STANZA'},
    {"roll": '25EE1035', "name": 'Sadgir Sairaj Santosh', "branch": 'EE', "cgpa": 5.45, "rank": 189, "hostelType": 'STANZA'},
    {"roll": '25CE1010', "name": 'Ankit Kumar', "branch": 'CE', "cgpa": 5.35, "rank": 190, "hostelType": 'STANZA'},
    {"roll": '25AI1051', "name": 'Stavan Prakash Gamit', "branch": 'AIDS', "cgpa": 5.35, "rank": 191, "hostelType": 'STANZA'},
    {"roll": '25ME1019', "name": 'Hathila Harshkumar Dineshbhai', "branch": 'ME', "cgpa": 5.33, "rank": 192, "hostelType": 'STANZA'},
    {"roll": '25AI1038', "name": 'Rakesh Kumar Malik', "branch": 'AIDS', "cgpa": 5.28, "rank": 193, "hostelType": 'STANZA'},
    {"roll": '25EE1021', "name": 'Kushagra Chaudhary', "branch": 'EE', "cgpa": 5.25, "rank": 194, "hostelType": 'STANZA'},
    {"roll": '25CE1014', "name": 'Ashmit Mishra', "branch": 'CE', "cgpa": 5.18, "rank": 195, "hostelType": 'STANZA'},
    {"roll": '25AI1021', "name": 'Lakdawala Fardin', "branch": 'AIDS', "cgpa": 5.15, "rank": 196, "hostelType": 'STANZA'},
    {"roll": '25ME1003', "name": 'Adarsh Thakur Lodhi', "branch": 'ME', "cgpa": 5.13, "rank": 197, "hostelType": 'STANZA'},
    {"roll": '25ME1011', "name": 'Bhukya Jeshwanth', "branch": 'ME', "cgpa": 5.13, "rank": 198, "hostelType": 'STANZA'},
    {"roll": '25ME1012', "name": 'Deepanshu Rathore', "branch": 'ME', "cgpa": 5.13, "rank": 199, "hostelType": 'STANZA'},
    {"roll": '25CE1047', "name": 'Ratnasheel Sharan', "branch": 'CE', "cgpa": 5.1, "rank": 200, "hostelType": 'STANZA'},
    {"roll": '25AI1029', "name": 'Navadiya Jils Hasmukhbhai', "branch": 'AIDS', "cgpa": 5.08, "rank": 201, "hostelType": 'STANZA'},
    {"roll": '25ME1051', "name": 'Vishwajeet Kumar', "branch": 'ME', "cgpa": 5.03, "rank": 202, "hostelType": 'STANZA'},
    {"roll": '25AI1050', "name": 'Snehangshu Sarkar', "branch": 'AIDS', "cgpa": 4.98, "rank": 203, "hostelType": 'STANZA'},
    {"roll": '25EE1025', "name": 'Muduku Viswa Nayakan Das', "branch": 'EE', "cgpa": 4.9, "rank": 204, "hostelType": 'STANZA'},
    {"roll": '25AI1037', "name": 'Rajkumar', "branch": 'AIDS', "cgpa": 4.9, "rank": 205, "hostelType": 'STANZA'},
    {"roll": '25CE1006', "name": 'Amaan Ahmad', "branch": 'CE', "cgpa": 4.88, "rank": 206, "hostelType": 'STANZA'},
    {"roll": '25CE1026', "name": 'Dev Pathak', "branch": 'CE', "cgpa": 4.88, "rank": 207, "hostelType": 'STANZA'},
    {"roll": '25AI1006', "name": 'Anik Gharami', "branch": 'AIDS', "cgpa": 4.88, "rank": 208, "hostelType": 'STANZA'},
    {"roll": '25EE1037', "name": 'Sarthak Dhayal', "branch": 'EE', "cgpa": 4.85, "rank": 209, "hostelType": 'STANZA'},
    {"roll": '25EC1035', "name": 'Nakshatra', "branch": 'ECE', "cgpa": 4.78, "rank": 210, "hostelType": 'STANZA'},
    {"roll": '25ME1052', "name": 'Zilla Akshay Kumar', "branch": 'ME', "cgpa": 4.78, "rank": 211, "hostelType": 'STANZA'},
    {"roll": '25CE1003', "name": 'Aditya Aman', "branch": 'CE', "cgpa": 4.78, "rank": 212, "hostelType": 'STANZA'},
    {"roll": '25AI1018', "name": 'Gavara Mahesh', "branch": 'AIDS', "cgpa": 4.78, "rank": 213, "hostelType": 'STANZA'},
    {"roll": '25AI1052', "name": 'Sumit Kumar Singh', "branch": 'AIDS', "cgpa": 4.78, "rank": 214, "hostelType": 'STANZA'},
    {"roll": '25ME1045', "name": 'Vansh Joshi', "branch": 'ME', "cgpa": 4.68, "rank": 215, "hostelType": 'STANZA'},
    {"roll": '25EC1057', "name": 'Sonu Baitha', "branch": 'ECE', "cgpa": 4.63, "rank": 216, "hostelType": 'STANZA'},
    {"roll": '25ME1028', "name": 'Marut Nandan', "branch": 'ME', "cgpa": 4.6, "rank": 217, "hostelType": 'STANZA'},
    {"roll": '25EC1029', "name": 'Lakshit Bhowray', "branch": 'ECE', "cgpa": 4.53, "rank": 218, "hostelType": 'STANZA'},
    {"roll": '25ME1018', "name": 'Harshwardhan', "branch": 'ME', "cgpa": 4.53, "rank": 219, "hostelType": 'STANZA'},
    {"roll": '25EE1017', "name": 'Dheeraj Meena', "branch": 'EE', "cgpa": 4.48, "rank": 220, "hostelType": 'STANZA'},
    {"roll": '25EE1049', "name": 'Vaibhav Kumar', "branch": 'EE', "cgpa": 4.35, "rank": 221, "hostelType": 'STANZA'},
    {"roll": '25CE1048', "name": 'Shambharkar Sankalp Ravi', "branch": 'CE', "cgpa": 4.28, "rank": 222, "hostelType": 'STANZA'},
    {"roll": '25ME1047', "name": 'Vedanta Kumar Ghosh', "branch": 'ME', "cgpa": 4.25, "rank": 223, "hostelType": 'STANZA'},
    {"roll": '25ME1050', "name": 'Vijay Kumar Meel', "branch": 'ME', "cgpa": 4.15, "rank": 224, "hostelType": 'STANZA'},
    {"roll": '25EE1010', "name": 'Bandi Rahul', "branch": 'EE', "cgpa": 4.1, "rank": 225, "hostelType": 'STANZA'},
    {"roll": '25AE1013', "name": 'Hardik Maida', "branch": 'AE', "cgpa": 4.09, "rank": 226, "hostelType": 'STANZA'},
    {"roll": '25ME1005', "name": 'Ankur Dahiya', "branch": 'ME', "cgpa": 4.08, "rank": 227, "hostelType": 'STANZA'},
    {"roll": '25EE1022', "name": 'Maloth Harsha', "branch": 'EE', "cgpa": 4.03, "rank": 228, "hostelType": 'STANZA'},
    {"roll": '25EC1024', "name": 'Kanishk Chetankumar Jethva', "branch": 'ECE', "cgpa": 3.95, "rank": 229, "hostelType": 'STANZA'},
    {"roll": '25AI1013', "name": 'Banoth Revanth', "branch": 'AIDS', "cgpa": 3.93, "rank": 230, "hostelType": 'STANZA'},
    {"roll": '25CE1055', "name": 'Shyam Ranjan Singh', "branch": 'CE', "cgpa": 3.83, "rank": 231, "hostelType": 'STANZA'},
    {"roll": '25AE1019', "name": 'Kethavath Eashwar', "branch": 'AE', "cgpa": 3.8, "rank": 232, "hostelType": 'STANZA'},
    {"roll": '25EE1029', "name": 'Priyanshu Kumar', "branch": 'EE', "cgpa": 3.78, "rank": 233, "hostelType": 'STANZA'},
    {"roll": '25CE1024', "name": 'Deepak Kumar Meena', "branch": 'CE', "cgpa": 3.65, "rank": 234, "hostelType": 'STANZA'},
    {"roll": '25EE1014', "name": 'Biswas Purnendu Pranabkumar', "branch": 'EE', "cgpa": 3.58, "rank": 235, "hostelType": 'STANZA'},
    {"roll": '25CE1057', "name": 'Trikant Singh', "branch": 'CE', "cgpa": 3.58, "rank": 236, "hostelType": 'STANZA'},
    {"roll": '25AE1012', "name": 'Fanat Mann Hasmukhbhai', "branch": 'AE', "cgpa": 3.52, "rank": 237, "hostelType": 'STANZA'},
    {"roll": '25EC1033', "name": 'Modirecha Sai Charan Teja Naik', "branch": 'ECE', "cgpa": 3.43, "rank": 238, "hostelType": 'STANZA'},
    {"roll": '25EE1050', "name": 'Virendra Kumar', "branch": 'EE', "cgpa": 3.23, "rank": 239, "hostelType": 'STANZA'},
    {"roll": '25ME1039', "name": 'Raviraj Dabhi', "branch": 'ME', "cgpa": 3.18, "rank": 240, "hostelType": 'STANZA'},
    {"roll": '25EC1040', "name": 'Punem Yashwanth Sai Vidhyadeep', "branch": 'ECE', "cgpa": 2.9, "rank": 241, "hostelType": 'STANZA'},
    {"roll": '25EE1031', "name": 'Rishabh Singh', "branch": 'EE', "cgpa": 2.8, "rank": 242, "hostelType": 'STANZA'},
    {"roll": '25ME1027', "name": 'Marlapudi Yaswanth', "branch": 'ME', "cgpa": 2.55, "rank": 243, "hostelType": 'STANZA'},
    {"roll": '25CE1033', "name": 'Kuldeep Meena', "branch": 'CE', "cgpa": 2.55, "rank": 244, "hostelType": 'STANZA'},
    {"roll": '25AE1035', "name": 'Tushan M B', "branch": 'AE', "cgpa": 2.23, "rank": 245, "hostelType": 'STANZA'},
    {"roll": '25AE1010', "name": 'Chukka Raymon Raj', "branch": 'AE', "cgpa": 2.18, "rank": 246, "hostelType": 'STANZA'},
    {"roll": '25EC1011', "name": 'Bikram Kumar', "branch": 'ECE', "cgpa": 1.93, "rank": 247, "hostelType": 'STANZA'},
    {"roll": '25AI1057', "name": 'Yogesh Yadav', "branch": 'AIDS', "cgpa": 1.7, "rank": 248, "hostelType": 'STANZA'},
    {"roll": '25AI1026', "name": 'Manish Kumar', "branch": 'AIDS', "cgpa": 1.68, "rank": 249, "hostelType": 'STANZA'},
    {"roll": '25EC1036', "name": 'Nikhil Bajranglal Meena', "branch": 'ECE', "cgpa": 1.58, "rank": 250, "hostelType": 'STANZA'},
    {"roll": '25CE1035', "name": 'Lakavath Yashaschandra Naik', "branch": 'CE', "cgpa": 1.5, "rank": 251, "hostelType": 'STANZA'},
    {"roll": '25EC1044', "name": 'Rongali Upendra', "branch": 'ECE', "cgpa": 1.45, "rank": 252, "hostelType": 'STANZA'},
    {"roll": '25ME1010', "name": 'Ayush Pandey', "branch": 'ME', "cgpa": 1.28, "rank": 253, "hostelType": 'STANZA'},
    {"roll": '25AI1027', "name": 'Mayank', "branch": 'AIDS', "cgpa": 1.15, "rank": 254, "hostelType": 'STANZA'},
    {"roll": '25CE1013', "name": 'Aryav Jangid', "branch": 'CE', "cgpa": 0.8, "rank": 255, "hostelType": 'STANZA'},
    {"roll": '25EC1049', "name": 'Sanjay Sharma', "branch": 'ECE', "cgpa": 0.58, "rank": 256, "hostelType": 'STANZA'},
    {"roll": '25EC1008', "name": 'Arnav Kumar', "branch": 'ECE', "cgpa": 0.53, "rank": 257, "hostelType": 'STANZA'},
    {"roll": '25EC1062', "name": 'Yadnesh Chandrashekhar Virpankar', "branch": 'ECE', "cgpa": 0.25, "rank": 258, "hostelType": 'STANZA'},
    {"roll": '25EC1016', "name": 'Dipayan Sarkar', "branch": 'ECE', "cgpa": 0.0, "rank": 259, "hostelType": 'STANZA'},
    {"roll": '25EE1051', "name": 'Yash Raj', "branch": 'EE', "cgpa": 0.0, "rank": 260, "hostelType": 'STANZA'},
]
